name:  League Loader Bug
description: Report a bug for an existing League Loader
title: "[LEAGUE LOADER]: "
labels:
  - bug
assignees:
  - joeyagreco

body:
- type: dropdown
  attributes:
    label: League Loader
    options:
     - ESPN
     - Sleeper
     - Yahoo
  validations:
    required: true

- type: textarea
  attributes:
    label: Summary
    description: Describe the bug briefly below.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: League Info
    description: "This is the league info you are using that is failing with the League Loader.\n This is not required but can help with debugging.\n PLEASE DO NOT SHARE LOGIN INFO!"
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Error Logs
    description: Paste any error logs here.
  validations:
    required: false
