name:  Stat Bug
description: Report a bug for an existing stat
title: "[BUG]: "
labels:
  - bug
assignees:
  - joeyagreco

body:
- type: dropdown
  attributes:
    label: Stat Category
    description: Select the category which this bug falls under.
    options:
     - AWAL
     - Game Outcome
     - Plus/Minus
     - Points Scored
     - Scoring Share
     - Scoring Standard Deviation
     - Single Score
     - Smart Wins
     - SSL
     - Team Summary
     - Not Listed
  validations:
    required: true

- type: textarea
  attributes:
    label: Summary
    description: Describe the bug briefly below.
  validations:
    required: true

- type: textarea
  attributes:
    label: League Info
    description: "This is the league info you are using that is failing with the League Loader.\n This is not required but can help with debugging.\n PLEASE DO NOT SHARE LOGIN INFO!"
  validations:
    required: false

- type: textarea
  attributes:
    label: Error Logs
    description: "Paste any error logs here.\n You can also put your League JSON here by using `print(myLeague.toJson)`."
  validations:
    required: false
