name: python version check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      manual:
        description: "Trigger the workflow manually"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current required Python version
        id: get-python-versions
        run: |
          MINIMUM_VERSION=$(grep -oP '__version_minimum_python__ = "\K.*(?=")' leeger/_version.py)
          echo "::set-output name=current_version::${MINIMUM_VERSION}"
          OLD_VERSION="${MINIMUM_VERSION%.*}.$((${MINIMUM_VERSION##*.}-1))"
          echo "::set-output name=old_version::${OLD_VERSION}"

      - name: Set up current Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ steps.get-python-versions.outputs.current_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: setup.py with current required Python version works
        run: |
          python setup.py install || echo "Current Python Version setup.py test failed"

      - name: Set up invalid Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ steps.get-python-versions.outputs.old_version }}

      - name: setup.py with invalid Python version fails
        run: |
          python setup.py install || echo "Old Python Version setup.py test failed"
